name: UI & API Automation Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name:  Checkout code
        uses: actions/checkout@v4

      - name:  Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name:  Install root dependencies
        run: npm install

      - name:  Install client (Cypress) dependencies
        working-directory: ./Client
        run: npm install

      - name:  Install Newman for API testing
        run: npm install -g newman

      - name:  Start frontend & backend
        run: npm start &
        env:
          CI: true

      - name:  Wait for servers to be ready
        run: npx wait-on http://localhost:5173/auth http://localhost:5000/api/items

      - name:  Run Cypress UI tests
        run: npx cypress run --project Client --spec "Client/cypress/e2e/ValidateLogin.cy.js,Client/cypress/e2e/CreateItem.cy.js,Client/cypress/e2e/UpdateItem.cy.js,Client/cypress/e2e/DeleteItem.cy.js"

      - name:  Run Postman API Tests via Newman
        run: npm run api:test

      - name:  Upload Cypress Snapshots
        uses: actions/upload-artifact@v4
        with:
          name: cypress-snapshots
          path: Client/cypress/screenshots
