name: Fullstack Test Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install root dependencies
        run: npm install

      - name: Install frontend (client) dependencies
        run: npm install
        working-directory: ./Client

      - name: Install backend (server) dependencies
        run: npm install
        working-directory: ./server

      - name: Install Cypress and Newman globally
        run: |
          npm install -g cypress
          npm install -g newman

      - name: Start fullstack app
        run: npm start &
        env:
          CI: true

      - name: Wait for services to boot
        run: sleep 25

      - name: Run Cypress Tests
        run: npm run cy:run

      - name: Upload Cypress Screenshots
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: Client/cypress/screenshots

      - name: Run Postman API Tests
        run: npm run api:test
